spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:35432/book-store-notification-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8083
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"

notifications:
  support-email: mayankyadav112@gmail.com
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders

  mail:
    host: ${MAIL_HOST:127.0.0.1}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:mailUser}
    password: ${MAIL_PASSWORD:mailPass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true