spring:
  application:
    name: order-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/book-store-order-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"

orders:
  catalog-service-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders

resilience4j:
  retry:
    instances:
      catalog-service:
        max-attempts: 2
        wait-duration: 500ms

  circuitbreaker:
    instances:
      catalog-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 4
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true